apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: confirm-order
  name: confirm-order
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: confirm-order
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: confirm-order
    spec:
      containers:
        - env:
            - name: WAIT_HOSTS
              value: confirm-order-db:27017, event-bus:9092
            - name: WAIT_TIMEOUT
              value: "120"
          image: confirm-order
          name: confirm-order
          ports:
            - containerPort: 4004
          resources: {}
      restartPolicy: Always
status: {}
