apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: create-card
  name: create-card
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: create-card
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: create-card
    spec:
      containers:
        - env:
            - name: WAIT_HOSTS
              value: create-card-db:27017, event-bus:9092
            - name: WAIT_TIMEOUT
              value: "120"
          image: create-card
          name: create-card
          ports:
            - containerPort: 4003
          resources: {}
      restartPolicy: Always
status: {}
