apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: create-card-db
  name: create-card-db
spec:
  ports:
    - name: "50002"
      port: 50002
      targetPort: 27017
  selector:
    io.kompose.service: create-card-db
status:
  loadBalancer: {}
