apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: debug
  name: debug
spec:
  ports:
    - name: "4005"
      port: 4005
      targetPort: 4005
  selector:
    io.kompose.service: debug
status:
  loadBalancer: {}
