apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: email-user-id-db
  name: email-user-id-db
spec:
  ports:
    - name: "50006"
      port: 50006
      targetPort: 27017
  selector:
    io.kompose.service: email-user-id-db
status:
  loadBalancer: {}
