apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: timers-db
  name: timers-db
spec:
  replicas: 1
  selector:
    matchLabels:
      io.kompose.service: timers-db
  strategy: {}
  template:
    metadata:
      annotations:
        kompose.cmd: kompose convert -f ../../docker-compose.yml
        kompose.version: 1.27.0 (HEAD)
      creationTimestamp: null
      labels:
        io.kompose.service: timers-db
    spec:
      containers:
        - image: timers-db
          name: timers-db
          ports:
            - containerPort: 27017
          resources: {}
      restartPolicy: Always
status: {}
