apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert -f ../../docker-compose.yml
    kompose.version: 1.27.0 (HEAD)
  creationTimestamp: null
  labels:
    io.kompose.service: timers-db
  name: timers-db
spec:
  ports:
    - name: "50005"
      port: 50005
      targetPort: 27017
  selector:
    io.kompose.service: timers-db
status:
  loadBalancer: {}
